config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'tweets#index'
  resources :tweets do
    resources :comments, only: :create
    collection do
      get :search
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet               #tweetsテーブルとのアソシエーション
  belongs_to :user                #usersテーブルとのアソシエーション
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments               #commentsテーブルとのアソシエーション

  validates :text, presence: true

  def self.search(search)
    return Tweet.all unless search
    Tweet.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments               #commentsテーブルとのアソシエーション

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure＿permitted＿parameters, if: :devise_controller?

  def configure＿permitted＿parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    render json:{ comment: comment, user_name: comment.user.nickname }
    # redirect_to "/tweets/#{comment.tweet.id}"   #コメントと結びつくツイートの詳細画面に遷移する
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/direct_messages_controller.rb
class DirectMessagesController < ApplicationController

  def index

  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, except: [:index, :new, :create, :search]
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
  end

  def destroy
    @tweet.destroy
  end

  def edit
  end

  def update
    @tweet.update(tweet_params)
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
      <h1 class="grid-6"><a href="/">PicTweet</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <a class="post" href="/tweets/new">投稿する</a>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright PicTweet 2019.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_form.html.erb
  <%= form.text_field :image, placeholder: "Image Url" %>
  <%= form.text_area :text, placeholder: "text" , rows: "10" %>
  <%= form.submit "SEND" %>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
      </li>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
  </span>
</div>

app/views/tweets/_tweet_content.html.erb
  <div class="content_post" style="background-image: url(<%= tweet.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <% if user_signed_in? && current_user.id == tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
        </li>
        <% end %>
      </ul>
    </div>
    <%= simple_format(tweet.text) %>
    <span class="name">
      <a href="/users/<%= tweet.user.id %>">
        <span>投稿者</span><%= tweet.user.nickname %>
      </a>
    </span>
  </div>

app/views/tweets/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= render partial: "tweet_content", locals: { tweet: @tweet } %>
  <%= form_with(model: @tweet, local: true) do |form| %>
    <h3>
      編集する
    </h3>
    <%= render partial: "form", locals: { form: form } %>
  <% end %>
</div>

app/views/tweets/index.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
  <%= form_with(model: @tweet, local: true) do |form| %>
    <h3>
      投稿する
    </h3>
    <%= render partial: "form", locals: { form: form } %>
  <% end %>
  </div>
</div>

app/views/tweets/search.html.erb
<%= form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
      <ul class="more_list">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
        <% end %>
      </ul>
    </div>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <!-- ここからフォーム -->
    <% if current_user %>
      <%= form_with(model: [@tweet, @comment], local: true, id: "comment_form") do |form| %>
        <%= form.text_area :text, placeholder: "コメントする" , rows: "2" %>
        <%= form.submit "SEND", id: "comment_form_button" %>
      <% end %>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/show.html.erb
  <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @tweets.each do |tweet| %>
      <div class="content_post" style="background-image: url(<%= tweet.image %>);">
        <%= simple_format(tweet.text) %>
      </div>
    <% end %>
  </div>